/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mujoco.java.example;

import org.mujoco.MuJoCoLib;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Starting "+MuJoCoLib.mj_versionString().getString());
        return true;
    }
}
